$(function(){
    $(".menu").on({
        mouseover:function(){
            $(".menu_sublist").show();
        },
        mouseout:function(){
             $(".menu_sublist").hide();
        }
    });
})